import type { ScrollWorldConfig } from "./engine";

export const flutterlyWorld: ScrollWorldConfig = {
  brand: { name: "Flutterly", href: "/" },
  hint: "scroll to fly through",
  nav: true,
  atmosphere: true,
  diveScroll: 1.55,
  connScroll: 0.9,
  cta: { label: "Book a call", href: "/book" },
  sections: [
    {
      id: "studio",
      label: "Studio",
      still: "/world/scene-studio.jpg",
      clip: "/world/dive-studio.mp4",
      accent: "#0E7A6B",
      linger: 0.38,
      eyebrow: "Flutterly Limited · Reading, UK",
      title: "Digital delivery for organisations people rely on",
      body: "We plan, build and support accessible websites, products, business email and campaigns — with a named person accountable from first call to handover.",
      tags: ["Websites", "Products", "Business email", "Campaigns"],
    },
    {
      id: "gp",
      label: "GP practices",
      still: "/world/scene-gp.jpg",
      clip: "/world/dive-gp.mp4",
      accent: "#005EB8",
      linger: 0.42,
      eyebrow: "For GP practices",
      title: "A practice website that takes work off the phones",
      body: "Clear signposting to appointments, prescriptions and the NHS App. Self-serve answers for common requests. Accessibility designed in from the start.",
      tags: ["NHS App", "WCAG 2.2 AA", "Self-serve"],
      cta: {
        primary: { label: "GP practice websites", href: "/gp-websites" },
        secondary: { label: "Preview a sample practice", href: "/demo/gp-practice" },
      },
    },
    {
      id: "care",
      label: "Care homes",
      still: "/world/scene-care.jpg",
      clip: "/world/dive-care.mp4",
      accent: "#C4843A",
      linger: 0.42,
      eyebrow: "For care homes",
      title: "A home families trust before they ever visit",
      body: "Warm, photo-led design for relatives researching care: CQC rating, visiting, admissions and recruitment handled properly — and honestly.",
      tags: ["Families first", "CQC", "Recruitment"],
      cta: {
        primary: { label: "Care home websites", href: "/care-home-websites" },
        secondary: { label: "Preview a sample home", href: "/demo/care-home" },
      },
    },
    {
      id: "workshop",
      label: "Delivery",
      still: "/world/scene-workshop.jpg",
      clip: "/world/dive-workshop.mp4",
      accent: "#16332C",
      linger: 0.36,
      eyebrow: "How we work",
      title: "One plan. One named lead. Work that stays useful.",
      body: "Websites, web and mobile products, Microsoft 365 or Google Workspace, and purposeful campaigns — connected, not handed between suppliers.",
      tags: ["Discover", "Plan", "Deliver", "Support"],
      cta: {
        primary: { label: "All services", href: "/services" },
        secondary: { label: "Packages", href: "/packages" },
      },
    },
    {
      id: "audit",
      label: "Audit",
      still: "/world/scene-audit.jpg",
      clip: "/world/dive-audit.mp4",
      accent: "#0E7A6B",
      linger: 0.45,
      scroll: 1.8,
      eyebrow: "Start here",
      title: "A written website audit before you commit",
      body: "Accessibility, speed, mobile, signposting, local search and security basics — reviewed in plain English, with the next step made obvious.",
      tags: ["Free written review", "UK-based", "Reply in one working day"],
      cta: {
        primary: { label: "Request a free audit", href: "/free-audit" },
        secondary: { label: "Book a call", href: "/book" },
      },
    },
  ],
};
